// Date: 4/26/2013 10:07:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package murdercoins.client.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCoinPressOld extends ModelBase
{
  //fields
    ModelRenderer TableBaseFront;
    ModelRenderer StandBaseBack;
    ModelRenderer StandBaseRight;
   // ModelRenderer StandBaseRight;
    ModelRenderer TableLegFL;
    ModelRenderer TableLegFR;
    ModelRenderer TableLegBR;
    ModelRenderer TableLegBL;
    ModelRenderer WheelBaseRight;
    ModelRenderer WheelSupportMidF;
    ModelRenderer WheelSupportMidB;
    ModelRenderer WheelTopBase;
   // ModelRenderer WheelRotorHousing;
    ModelRenderer StandTopRight;
    ModelRenderer TableTopFront;
    //ModelRenderer StandTopRight;
    ModelRenderer WheelRotorHousing;
    ModelRenderer ChainWell;
    ModelRenderer Rotor;
    ModelRenderer StandTopBack;
    //ModelRenderer PressHousingInsideR;
    ModelRenderer PressHousingL;
    ModelRenderer PressHousingTopRounder;
    ModelRenderer PressHousingTop;
    ModelRenderer PressHousingR;
    ModelRenderer PressHousingInsideR;
    ModelRenderer RotorB;
    ModelRenderer RotorBHouseing;
    ModelRenderer ChainBWell;
    ModelRenderer CoinCatch;
    ModelRenderer WheelAnimateSafe;
    ModelRenderer PressHead;
    ModelRenderer Presspiston;
    ModelRenderer PresspistonBase;
  
  public ModelCoinPressOld()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      TableBaseFront = new ModelRenderer(this, 0, 24);
      TableBaseFront.addBox(-7F, 0F, -16F, 23, 3, 4);
      TableBaseFront.setRotationPoint(8F, 21F, 8F);
      TableBaseFront.setTextureSize(128, 64);
      TableBaseFront.mirror = true;
      setRotation(TableBaseFront, 0F, 0F, 0F);
      StandBaseBack = new ModelRenderer(this, 0, 24);
      StandBaseBack.addBox(-7F, 0F, 8F, 23, 3, 4);
      StandBaseBack.setRotationPoint(8F, 21F, 8F);
      StandBaseBack.setTextureSize(128, 64);
      StandBaseBack.mirror = true;
      setRotation(StandBaseBack, 0F, 0F, 0F);
      StandBaseRight = new ModelRenderer(this, 0, 0);
      StandBaseRight.addBox(-7F, 0F, -12F, 4, 3, 20);
      StandBaseRight.setRotationPoint(8F, 21F, 8F);
      StandBaseRight.setTextureSize(128, 64);
      StandBaseRight.mirror = true;
      setRotation(StandBaseRight, 0F, 0F, 0F);
      StandBaseRight = new ModelRenderer(this, 0, 0);
      StandBaseRight.addBox(12F, 0F, -12F, 4, 3, 20);
      StandBaseRight.setRotationPoint(8F, 21F, 8F);
      StandBaseRight.setTextureSize(128, 64);
      StandBaseRight.mirror = true;
      setRotation(StandBaseRight, 0F, 0F, 0F);
      TableLegFL = new ModelRenderer(this, 49, 1);
      TableLegFL.addBox(-6F, -7F, -15F, 2, 7, 2);
      TableLegFL.setRotationPoint(8F, 21F, 8F);
      TableLegFL.setTextureSize(128, 64);
      TableLegFL.mirror = true;
      setRotation(TableLegFL, 0F, 0F, 0F);
      TableLegFR = new ModelRenderer(this, 49, 1);
      TableLegFR.addBox(13F, -7F, -15F, 2, 7, 2);
      TableLegFR.setRotationPoint(8F, 21F, 8F);
      TableLegFR.setTextureSize(128, 64);
      TableLegFR.mirror = true;
      setRotation(TableLegFR, 0F, 0F, 0F);
      TableLegBR = new ModelRenderer(this, 49, 1);
      TableLegBR.addBox(-6F, -7F, 9F, 2, 7, 2);
      TableLegBR.setRotationPoint(8F, 21F, 8F);
      TableLegBR.setTextureSize(128, 64);
      TableLegBR.mirror = true;
      setRotation(TableLegBR, 0F, 0F, 0F);
      TableLegBL = new ModelRenderer(this, 49, 1);
      TableLegBL.addBox(13F, -7F, 9F, 2, 7, 2);
      TableLegBL.setRotationPoint(8F, 21F, 8F);
      TableLegBL.setTextureSize(128, 64);
      TableLegBL.mirror = true;
      setRotation(TableLegBL, 0F, 0F, 0F);
      WheelBaseRight = new ModelRenderer(this, 3, 35);
      WheelBaseRight.addBox(-14F, 0F, -5F, 7, 3, 10);
      WheelBaseRight.setRotationPoint(8F, 21F, 8F);
      WheelBaseRight.setTextureSize(128, 64);
      WheelBaseRight.mirror = true;
      setRotation(WheelBaseRight, 0F, 0F, 0F);
      WheelSupportMidF = new ModelRenderer(this, 0, 32);
      WheelSupportMidF.addBox(-13.9F, -10F, -4F, 5, 11, 1);
      WheelSupportMidF.setRotationPoint(8F, 21F, 8F);
      WheelSupportMidF.setTextureSize(128, 64);
      WheelSupportMidF.mirror = true;
      setRotation(WheelSupportMidF, -0.2094395F, 0F, 0F);
     // WheelSupportMidB.mirror = true;
      WheelSupportMidB = new ModelRenderer(this, 0, 32);
      WheelSupportMidB.addBox(-13.9F, -10F, 3F, 5, 11, 1);
      WheelSupportMidB.setRotationPoint(8F, 21F, 8F);
      WheelSupportMidB.setTextureSize(128, 64);
      WheelSupportMidB.mirror = true;
      setRotation(WheelSupportMidB, 0.2094395F, 0F, 0F);
      WheelSupportMidB.mirror = false;
      WheelTopBase = new ModelRenderer(this, 49, 11);
      WheelTopBase.addBox(-14F, -11F, -2F, 5, 1, 4);
      WheelTopBase.setRotationPoint(8F, 21F, 8F);
      WheelTopBase.setTextureSize(128, 64);
      WheelTopBase.mirror = true;
      setRotation(WheelTopBase, 0F, 0F, 0F);
      WheelRotorHousing = new ModelRenderer(this, 34, 11);
      WheelRotorHousing.addBox(-13F, -14F, -2F, 3, 3, 4);
      WheelRotorHousing.setRotationPoint(8F, 21F, 8F);
      WheelRotorHousing.setTextureSize(128, 64);
      WheelRotorHousing.mirror = true;
      setRotation(WheelRotorHousing, 0F, 0F, 0F);
      //StandTopRight.mirror = true;
      StandTopRight = new ModelRenderer(this, 49, 0);
      StandTopRight.addBox(-7F, -10F, -7F, 8, 3, 19);
      StandTopRight.setRotationPoint(8F, 21F, 8F);
      StandTopRight.setTextureSize(128, 64);
      StandTopRight.mirror = true;
      setRotation(StandTopRight, 0F, 0F, 0F);
      StandTopRight.mirror = false;
      TableTopFront = new ModelRenderer(this, 1, 52);
      TableTopFront.addBox(-7F, -10F, -16F, 23, 3, 9);
      TableTopFront.setRotationPoint(8F, 21F, 8F);
      TableTopFront.setTextureSize(128, 64);
      TableTopFront.mirror = true;
      setRotation(TableTopFront, 0F, 0F, 0F);
      StandTopRight = new ModelRenderer(this, 49, 0);
      StandTopRight.addBox(8F, -10F, -7F, 8, 3, 19);
      StandTopRight.setRotationPoint(8F, 21F, 8F);
      StandTopRight.setTextureSize(128, 64);
      StandTopRight.mirror = true;
      setRotation(StandTopRight, 0F, 0F, 0F);
      WheelRotorHousing = new ModelRenderer(this, 34, 11);
      WheelRotorHousing.addBox(-7F, -14F, -2F, 3, 4, 4);
      WheelRotorHousing.setRotationPoint(8F, 21F, 8F);
      WheelRotorHousing.setTextureSize(128, 64);
      WheelRotorHousing.mirror = true;
      setRotation(WheelRotorHousing, 0F, 0F, 0F);
      ChainWell = new ModelRenderer(this, 90, 39);
      ChainWell.addBox(0.1F, -4F, -3F, 1, 8, 16);
      ChainWell.setRotationPoint(0F, 9F, 8F);
      ChainWell.setTextureSize(128, 64);
      ChainWell.mirror = true;
      setRotation(ChainWell, -0.3665191F, 0F, 0F);
      Rotor = new ModelRenderer(this, 34, 8);
      Rotor.addBox(-10F, -13F, -0.5F, 3, 1, 1);
      Rotor.setRotationPoint(8F, 21F, 8F);
      Rotor.setTextureSize(128, 64);
      Rotor.mirror = true;
      setRotation(Rotor, 0F, 0F, 0F);
      StandTopBack = new ModelRenderer(this, 54, 23);
      StandTopBack.addBox(1F, -10F, -7F, 7, 3, 19);
      StandTopBack.setRotationPoint(8F, 21F, 8F);
      StandTopBack.setTextureSize(128, 64);
      StandTopBack.mirror = true;
      setRotation(StandTopBack, 0F, 0F, 0F);
      PressHousingInsideR = new ModelRenderer(this, 29, 32);
      PressHousingInsideR.addBox(1F, -17F, -11F, 2, 2, 4);
      PressHousingInsideR.setRotationPoint(8F, 21F, 8F);
      PressHousingInsideR.setTextureSize(128, 64);
      PressHousingInsideR.mirror = true;
      setRotation(PressHousingInsideR, 0F, 0F, 0F);
     // PressHousingL.mirror = true;
      PressHousingL = new ModelRenderer(this, 5, 8);
      PressHousingL.addBox(8F, -17F, -11F, 3, 7, 4);
      PressHousingL.setRotationPoint(8F, 21F, 8F);
      PressHousingL.setTextureSize(128, 64);
      PressHousingL.mirror = true;
      setRotation(PressHousingL, 0F, 0F, 0F);
      PressHousingL.mirror = false;
      PressHousingTopRounder = new ModelRenderer(this, 85, 0);
      PressHousingTopRounder.addBox(1F, -20F, -11F, 7, 1, 4);
      PressHousingTopRounder.setRotationPoint(8F, 21F, 8F);
      PressHousingTopRounder.setTextureSize(128, 64);
      PressHousingTopRounder.mirror = true;
      setRotation(PressHousingTopRounder, 0F, 0F, 0F);
      PressHousingTop = new ModelRenderer(this, 73, 46);
      PressHousingTop.addBox(-1F, -19F, -11F, 11, 2, 4);
      PressHousingTop.setRotationPoint(8F, 21F, 8F);
      PressHousingTop.setTextureSize(128, 64);
      PressHousingTop.mirror = true;
      setRotation(PressHousingTop, 0F, 0F, 0F);
      PressHousingR = new ModelRenderer(this, 5, 8);
      PressHousingR.addBox(-2F, -17F, -11F, 3, 7, 4);
      PressHousingR.setRotationPoint(8F, 21F, 8F);
      PressHousingR.setTextureSize(128, 64);
      PressHousingR.mirror = true;
      setRotation(PressHousingR, 0F, 0F, 0F);
      PressHousingInsideR.mirror = true;
      PressHousingInsideR = new ModelRenderer(this, 29, 32);
      PressHousingInsideR.addBox(6F, -17F, -11F, 2, 2, 4);
      PressHousingInsideR.setRotationPoint(8F, 21F, 8F);
      PressHousingInsideR.setTextureSize(128, 64);
      PressHousingInsideR.mirror = true;
      setRotation(PressHousingInsideR, 0F, 0F, 0F);
      PressHousingInsideR.mirror = false;
      RotorB = new ModelRenderer(this, 34, 8);
      RotorB.addBox(-4F, -13F, -0.5F, 4, 1, 1);
      RotorB.setRotationPoint(8F, 21F, 8F);
      RotorB.setTextureSize(128, 64);
      RotorB.mirror = true;
      setRotation(RotorB, 0F, 0F, 0F);
      RotorBHouseing = new ModelRenderer(this, 34, 1);
      RotorBHouseing.addBox(-1F, -14F, -1.5F, 2, 4, 3);
      RotorBHouseing.setRotationPoint(8F, 21F, 8F);
      RotorBHouseing.setTextureSize(128, 64);
      RotorBHouseing.mirror = true;
      setRotation(RotorBHouseing, 0F, 0F, 0F);
      ChainBWell = new ModelRenderer(this, 53, 29);
      ChainBWell.addBox(-0.9F, -14F, -9.5F, 1, 4, 7);
      ChainBWell.setRotationPoint(8F, 21F, 8F);
      ChainBWell.setTextureSize(128, 64);
      ChainBWell.mirror = true;
      setRotation(ChainBWell, -0.1570796F, 0F, 0F);
      CoinCatch = new ModelRenderer(this, 67, 53);
      CoinCatch.addBox(1F, -9F, 12F, 7, 4, 4);
      CoinCatch.setRotationPoint(8F, 21F, 8F);
      CoinCatch.setTextureSize(128, 64);
      CoinCatch.mirror = true;
      setRotation(CoinCatch, 0F, 0F, 0F);
      WheelAnimateSafe = new ModelRenderer(this, 90, 7);
      WheelAnimateSafe.addBox(-1F, -8F, -8F, 1, 16, 16);
      WheelAnimateSafe.setRotationPoint(0F, 9F, 8F);
      WheelAnimateSafe.setTextureSize(128, 64);
      WheelAnimateSafe.mirror = true;
      setRotation(WheelAnimateSafe, 0F, 0F, 0F);
      PressHead = new ModelRenderer(this, 0, 1);
      PressHead.addBox(-3F, 5F, -2F, 6, 1, 4);
      PressHead.setRotationPoint(12.5F, 5F, -1F);
      PressHead.setTextureSize(128, 64);
      PressHead.mirror = true;
      setRotation(PressHead, 0F, 0F, 0F);
      Presspiston = new ModelRenderer(this, 58, 6);
      Presspiston.addBox(-0.5F, 2F, -0.5F, 1, 3, 1);
      Presspiston.setRotationPoint(12.5F, 5F, -1F);
      Presspiston.setTextureSize(128, 64);
      Presspiston.mirror = true;
      setRotation(Presspiston, 0F, 0F, 0F);
      PresspistonBase = new ModelRenderer(this, 58, 1);
      PresspistonBase.addBox(-1F, -1F, -1F, 2, 3, 2);
      PresspistonBase.setRotationPoint(12.5F, 5F, -1F);
      PresspistonBase.setTextureSize(128, 64);
      PresspistonBase.mirror = true;
      setRotation(PresspistonBase, 0F, 0F, 0F);
  }
  public void render(float f5)
  {
	  TableBaseFront.render(f5);
	    StandBaseBack.render(f5);
	    StandBaseRight.render(f5);
	    StandBaseRight.render(f5);
	    TableLegFL.render(f5);
	    TableLegFR.render(f5);
	    TableLegBR.render(f5);
	    TableLegBL.render(f5);
	    WheelBaseRight.render(f5);
	    WheelSupportMidF.render(f5);
	    WheelSupportMidB.render(f5);
	    WheelTopBase.render(f5);
	    WheelRotorHousing.render(f5);
	    StandTopRight.render(f5);
	    TableTopFront.render(f5);
	    StandTopRight.render(f5);
	    WheelRotorHousing.render(f5);
	    ChainWell.render(f5);
	    Rotor.render(f5);
	    StandTopBack.render(f5);
	    PressHousingInsideR.render(f5);
	    PressHousingL.render(f5);
	    PressHousingTopRounder.render(f5);
	    PressHousingTop.render(f5);
	    PressHousingR.render(f5);
	    PressHousingInsideR.render(f5);
	    RotorB.render(f5);
	    RotorBHouseing.render(f5);
	    ChainBWell.render(f5);
	    CoinCatch.render(f5);
	    WheelAnimateSafe.render(f5);
	    PressHead.render(f5);
	    Presspiston.render(f5);
	    PresspistonBase.render(f5);
  }
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    TableBaseFront.render(f5);
    StandBaseBack.render(f5);
    StandBaseRight.render(f5);
    StandBaseRight.render(f5);
    TableLegFL.render(f5);
    TableLegFR.render(f5);
    TableLegBR.render(f5);
    TableLegBL.render(f5);
    WheelBaseRight.render(f5);
    WheelSupportMidF.render(f5);
    WheelSupportMidB.render(f5);
    WheelTopBase.render(f5);
    WheelRotorHousing.render(f5);
    StandTopRight.render(f5);
    TableTopFront.render(f5);
    StandTopRight.render(f5);
    WheelRotorHousing.render(f5);
    ChainWell.render(f5);
    Rotor.render(f5);
    StandTopBack.render(f5);
    PressHousingInsideR.render(f5);
    PressHousingL.render(f5);
    PressHousingTopRounder.render(f5);
    PressHousingTop.render(f5);
    PressHousingR.render(f5);
    PressHousingInsideR.render(f5);
    RotorB.render(f5);
    RotorBHouseing.render(f5);
    ChainBWell.render(f5);
    CoinCatch.render(f5);
    WheelAnimateSafe.render(f5);
    PressHead.render(f5);
    Presspiston.render(f5);
    PresspistonBase.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
